=== parv1601/traffic-control-system/schemas/traffic_stream.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ct="http://smarttraffic/common"
           targetNamespace="http://smarttraffic/stream"
           xmlns="http://smarttraffic/stream"
           elementFormDefault="qualified">

    <xs:import namespace="http://smarttraffic/common"
               schemaLocation="restrictions.xsd"/>

    <xs:element name="TrafficStreamPacket">

        <xs:complexType>

            <xs:sequence>

                <xs:element name="PacketID"
                            type="ct:PacketIDType"/>

                <xs:element name="Timestamp"
                            type="xs:dateTime"/>

                <xs:element name="IntersectionID"
                            type="ct:IntersectionIDType"/>

                <xs:element name="RoadID"
                            type="ct:RoadIDType"/>

                <xs:element name="VehicleCount"
                            type="ct:VehicleCountType"/>

                <xs:element name="AverageSpeed"
                            type="ct:SpeedType"/>

                <xs:element name="TrafficDensity"
                            type="ct:DensityType"/>

                <xs:element name="EmergencyVehicle"
                            type="xs:boolean"
                            minOccurs="0"/>

                <xs:element name="PedestrianWaiting"
                            type="xs:boolean"
                            minOccurs="0"/>

            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>

=== parv1601/traffic-control-system/xml_instances/streams/stream_pkt_000002.xml
<?xml version="1.0" encoding="UTF-8"?>

<TrafficStreamPacket xmlns="http://smarttraffic/stream"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://smarttraffic/stream ../schemas/traffic_stream.xsd">

    <PacketID>PKT_000002</PacketID>

    <Timestamp>2026-02-14T10:00:02</Timestamp>

    <IntersectionID>I101</IntersectionID>

    <RoadID>I101_R2</RoadID>

    <VehicleCount>9</VehicleCount>

    <EmergencyVehicle>true</EmergencyVehicle>

    <PedestrianWaiting>false</PedestrianWaiting>

</TrafficStreamPacket>
